### ISSUE TITLE
8.0.0 roadmap

### ISSUE THREAD

**Issue by gulien** [gotenberg/gotenberg#710]
Hello folks 👋 ,

I'm planning to release Gotenberg `8.0.0` before the end of the year. It will be a "light" release, i.e., if you're using the latest `7.x` version, all you'll have to do is remove the deprecated flags, form fields and so on. Checking your Gotenberg instance(s) logging entries should be enough to know if you're using any deprecated features 👍 

### 7.10.0

- [x] Use Debian 12 (a.k.a. bookworm) and latest LibreOffice version (#576 - done in #697). 
- [x] "Stateful" Chromium, i.e., only one long-running browser instance in order to prevent too much memory leaks (#642) and ease the scalability strategy (done in #705).
- [x] Switch LibreOffice module to same "supervisor" as Chromium (done in #708).
- [x] Edge release: a push on `main` branch now triggers the build of `gotenberg/gotenberg:edge` and `gotenberg/gotenberg:edge-cloudrun`. Good to know: the live demo is based on this new version.
- [x] Fix `armhf` build (#709).
- [x] Refactor `convert` method from PDF engines to be more generic (no more PDF format, but PDF Archive, PDF UA, etc.).
- [x] Refactor godoc and tests.
- [x] (optional) Replace `unoconv` with a new `unoconverter` Python project.

### 8.0.0

- [x] Remove all deprecated features (done in #726).
- [x] Chromium: capture screenshots (done in #765).
- [x] Chromium: performance mode, e.g.,`skipNetworkIdleEvent` (done in #749).
- [x] Chromium: return error if status code does not match a specified value (#613 - done in #755).
- [x] Chromium: flag to clear cache after each request (#753 - done in #756).
- [x] Set to v8 (done in #767).

---

Do you want to help? Consider testing `gotenberg/gotenberg:edge`, thanks!

**Comment by bedla** [comment]
Hi, I have a question: do you some plans to take a look into vulnerabilites detected in the image?
```
docker run aquasec/trivy image gotenberg/gotenberg:latest
```
Anyways, thx for your project :)
Ivos

**Comment by gulien** [comment]
Dependencies will be updated so I guess it will take care of « vulnerabilities ».

**Comment by stumpylog** [comment]
Regarding deprecated flags/options, is there an API to check the version of Gotenberg a client is communicating with?  I maintain a little library for talking to Gotenberg, so the version might be basically anything somewhat recent, depending on the user.

**Comment by gulien** [comment]
Best option is to release a major version of your client. For instance, `gotenberg/gotenberg-php` 1.x will not be compatible with Gotenberg 8, but 2.x will.

**Comment by eloircorona** [comment]
Hello :)

Today, when there was a reboot in one of the pods, the version was updated and it showed me the following error message. Could u help me?

`A Docker-powered stateless API for PDF files.
Version: 7.10.0
-------------------------------------------------------
[SYSTEM] modules: api chromium libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
Flag --uno-listener-restart-threshold has been deprecated, use the libreOffice-restart-after property instead
Flag --uno-listener-start-timeout has been deprecated, use the libreOffice-start-timeout property instead
panic: trying to get int64 value of flag of type int

goroutine 1 [running]:
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*ParsedFlags).MustInt64(0xc0000b6c00?, {0xf10e34?, 0xc000048fc0?})
	/home/pkg/gotenberg/flags.go:88 +0x6b
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*ParsedFlags).MustDeprecatedInt64(0xc000365088, {0xf10e34, 0x1e}, {0xf08bab, 0x19})
	/home/pkg/gotenberg/flags.go:99 +0x4a
github.com/gotenberg/gotenberg/v7/pkg/modules/libreoffice/api.(*Api).Provision(0xc000088360, 0xc0000b98f0)
	/home/pkg/modules/libreoffice/api/api.go:142 +0x338
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).loadModule(0xc0000b98f0, {0xef81ef, 0xf}, {0xe8fbc0?, 0xc000088360})
	/home/pkg/gotenberg/context.go:107 +0x67
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).Modules(0xc0000b98f0, {0xd5d780?, 0xc0000507c0?})
	/home/pkg/gotenberg/context.go:89 +0x275
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).Module(0xc00004e018?, {0xd5d780, 0xc0000507c0})
	/home/pkg/gotenberg/context.go:49 +0x25
github.com/gotenberg/gotenberg/v7/pkg/modules/libreoffice/pdfengine.(*LibreOfficePdfEngine).Provision(0xc0000507b0, 0xdf82c0?)
	/home/pkg/modules/libreoffice/pdfengine/pdfengine.go:34 +0x3c
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).loadModule(0xc0000b98f0, {0xf02464, 0x15}, {0xdf82c0?, 0xc0000507b0})
	/home/pkg/gotenberg/context.go:107 +0x67
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).Modules(0xc0000b98f0, {0xd5d240?, 0xc000365528?})
	/home/pkg/gotenberg/context.go:89 +0x275
github.com/gotenberg/gotenberg/v7/pkg/modules/pdfengines.(*PdfEngines).Provision(0xc0000c5340, 0xc0000b98f0)
	/home/pkg/modules/pdfengines/pdfengines.go:69 +0x1ba
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).loadModule(0xc0000b98f0, {0xef11b5, 0xa}, {0xe3cb20?, 0xc0000c5340})
	/home/pkg/gotenberg/context.go:107 +0x67
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).Modules(0xc0000b98f0, {0xd5d280?, 0xc000050720?})
	/home/pkg/gotenberg/context.go:89 +0x275
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).Module(0xc000048042?, {0xd5d280, 0xc000050720})
	/home/pkg/gotenberg/context.go:49 +0x25
github.com/gotenberg/gotenberg/v7/pkg/modules/chromium.(*Chromium).Provision(0xc0000d8b40, 0xc0000b98f0)
	/home/pkg/modules/chromium/chromium.go:296 +0x6aa
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).loadModule(0xc0000b98f0, {0xeed766, 0x8}, {0xe8fac0?, 0xc0000d8b40})
	/home/pkg/gotenberg/context.go:107 +0x67
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).Modules(0xc0000b98f0, {0xd5d540?, 0xc000365b30?})
	/home/pkg/gotenberg/context.go:89 +0x275
github.com/gotenberg/gotenberg/v7/pkg/modules/api.(*Api).Provision(0xc0000d4210, 0xc0000b98f0)
	/home/pkg/modules/api/api.go:216 +0x21e
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).loadModule(0xc0000b98f0, {0xee6830, 0x3}, {0xe3c5e0?, 0xc0000d4210})
	/home/pkg/gotenberg/context.go:107 +0x67
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*Context).Modules(0xc0000b98f0, {0xd5d080?, 0xc000365eb8?})
	/home/pkg/gotenberg/context.go:89 +0x275
github.com/gotenberg/gotenberg/v7/cmd.Run()
	/home/cmd/gotenberg.go:68 +0x44b
main.main()
	/home/cmd/gotenberg/main.go:10 +0xf`

**Comment by maj2c** [comment]
Hi,
First of all thank you for the great job and making it available for everybody :)
Is it possible to make a docker release with latest features but based on Debian 11 instead of 12?
The cloud host I am using does not support Debian 12. Thus, I am forced to stay on release 7.9.2-cloudrun.
Thank you in advance.

**Comment by gulien** [comment]
Hello @maj2c 👋 I don’t want to create additional release with another Debian version, because the Go code and the Dockerfile dependencies are quite interdependent.
